### ISSUE TITLE
It's needs accept @mipmap folders

### ISSUE THREAD

**Issue by ppamorim** [Ereza/CustomActivityOnCrash#11]
Hi, I notice that library only accept @drawable folder, you need to create a alternative to support @mipmap too. My app uses mipmap and it's unwanted for create these folders only to this library.

**Comment by Ereza** [comment]
Hi:

I don't see the benefit of using mipmap on this image if you don't use it on animations or anything like that. And if you do, you are already using your own custom activity, so you can use a mipmap there if you wish... Or maybe I'm wrong and there is benefit on using mipmaps other than for animations (or launcher icons)?

Can you elaborate?

Thanks!

**Comment by ppamorim** [comment]
@Ereza Before all, What do you think about using that implementation only with code? The override of resource can be a little bit confuse to some developers.

**Comment by Ereza** [comment]
@ppamorim You mean specifying the drawable with something like: `CustomActivityOnCrash.setDefaultErrorActivityDrawable(R.drawable.my_image)`?

I guess it's feasible, but I don't see how overriding a drawable is more confusing than overriding strings...

**Comment by ppamorim** [comment]
@Ereza Yes, but you can maintain this override of the drawable with strings and implements the method way too.

**Comment by Ereza** [comment]
You're right, I'll do that.

**Comment by Ereza** [comment]
Hi, this has been implemented in the 1.4.0 release. A new method `CustomActivityOnCrash.setDefaultErrorActivityDrawable(int);` is available, and you can pass in a drawable or mipmap id.
Thanks for your suggestion!
