### ISSUE TITLE
Hi i want to ask a question about StackTrace.

### ISSUE THREAD

**Issue by deekea** [Ereza/CustomActivityOnCrash#20]
The CustomActivityOnCrash.getStackTraceFromIntent(...) doesn't not return the full message. For example ...... android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2528) ... 10 more , How to get the 10 more error line ?

**Comment by Ereza** [comment]
Hi @deekea, the returned stacktrace is exactly the same that you would get by printing the stack trace to LogCat. This is a Java issue, not a behavior of this library. I personally don't know how to make it print all lines, but you shouldn't need them anyway since they are framework-related.
