### ISSUE TITLE
ClassNotFoundException if some other app is using the error intent filter

### ISSUE THREAD

**Issue by jsoriase** [Ereza/CustomActivityOnCrash#21]
If the device has another app with CustomActivityOnCrash which has an Activity with "cat.ereza.customactivityoncrash.ERROR" as intent filter and you dont, CustomActivityOnCrash.getErrorActivityClassWithIntentFilter() will throw a ClassNotFoundException

**Comment by adrielcafe** [comment]
Same problem here. I have two different apps using this lib. When the second app try to open a custom Activity the app throws this exception.

**Comment by Ereza** [comment]
Fixed in 1.5.0. The library now filters only activities on the current package.

**Comment by adrielcafe** [comment]
Thank you!
