### ISSUE TITLE
custom theme

### ISSUE THREAD

**Issue by chrischen-melb** [Ereza/CustomActivityOnCrash#26]
hi, awesome stuff you made.

not an expert on Android, but i'm trying to use this to style the crash activity, mainly its action bar colors but with no success

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
    </style>

    <style name="CustomActivityOnCrashTheme" parent="AppTheme" />

</resources>
```

my app's activity action bar is styled in red colors, whoever the crash activity action bar is in blue

**Comment by mnive93** [comment]
Hello,
The same issue is happening for me. Is this fixed?

**Comment by TheLGameS** [comment]
Did not work!

**Comment by Ereza** [comment]
Hi @chrischen-melb, sorry for the long delay in my response.

This should be fixed in the current development version since it now uses AppCompat. It will soon be published in version 2.0.0 of the library.

Please reopen this issue if this isn't fixed, and thanks for reporting the problem.

**Comment by Ereza** [comment]
Hi, latest version is now available on Maven Central. Let me know if you have any other issue!

**Comment by sujatha2016** [comment]
I tried this but not working. 
My apps primaryCOlor is white so I cannot see that button text Error Details due to this. Is there anyway we can achieve this.
