### ISSUE TITLE
Does not work with Firebase

### ISSUE THREAD

**Issue by k0shk0sh** [Ereza/CustomActivityOnCrash#28]
as per the title says, the library does not catch the crash when using Firebase crash reporting.

maybe this could be helpful ?
http://stackoverflow.com/questions/38048314/deal-with-firebase-crash-reporting-and-custom-application-class-with-custom-unca

**Comment by android-dataticket** [comment]
i'm only using firebase notifications and this is still breaking this library - any help is greatly appreciated:

http://stackoverflow.com/questions/43286225/using-a-custom-crash-handler-with-firebase-installed

**Comment by Ereza** [comment]
Hi @k0shk0sh, sorry for the long long delay.

Should work with the current development version. The only problem with the current production version should be that crashes don't get reported to Firebase, but the rest should work.

I'll release the new version soon as 2.0.0. Thanks for reporting the issue.

**Comment by k0shk0sh** [comment]
@Ereza I guess then in this case the issue shouldn't be closed yet? but rather still in progress? because it didn't solve any issue here but rather implemented a bug where now crashes don't get reported to firebase as you mentioned.

**Comment by Ereza** [comment]
Hi @k0shk0sh, the latest version 2.0.0 is already on Maven Central. Let me know if the issue is still there!

**Comment by lucazin** [comment]
Hi Ereza,  i put the version 2.0.0 but i'm still not receiving any crash from firebase

can you help me ?

**Comment by lnicolet** [comment]
Same here, nothing gets reported to Firebase console
