### ISSUE TITLE
restartApplicationWithIntent() more than Home key

### ISSUE THREAD

**Issue by zengcanxiang** [Ereza/CustomActivityOnCrash#29]
me App crash,according to sample,do restartApplicationWithIntent() method.  
Then, press Home key,perhaps repeat this operation.  
App Stack no clean .
if in LAUNCHER Activity onCreate() add  following code,would not produce.  
But I don't know why.
```java
 if (!isTaskRoot()) {
            finish();
            return;
  }
```

**Comment by Ereza** [comment]
Hello, @zengcanxiang, sorry for the long time.

Maybe you figured it out already. Are you using a custom error activity? If so, can you reproduce the issue with the default error activity?

Thanks!

**Comment by Ereza** [comment]
Closed due to lack of activity. If you still need help feel free to reopen it or create a new issue. Thanks!

**Comment by zengcanxiang** [comment]
Very sorry, did not respond to you in a timely manner, because the work led to a period of time did not come to pay attention to this problem.  
the default error activityis also like this.  
When I press the home button, did not return to the home page, but restarted.
but file not upload...
http://o6y6mbc2m.bkt.clouddn.com/%E6%B7%B1%E5%BA%A6%E5%BD%95%E5%B1%8F_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20170614145808.gif

**Comment by Ereza** [comment]
Thanks for the feedback @zengcanxiang, I have not been able to reproduce your problem specifically, but when checking, I found out that the root activity becomes duplicated after restarting the app from the error activity, them pressing home, and then launching the app again. It's likely that this is related to your issue. Could you try with the current development version? (you'll have to import the library manually)

Thanks again for your help!

**Comment by zengcanxiang** [comment]
@Ereza Okay, I'll test it.Thanks for the help you have provided.

**Comment by zengcanxiang** [comment]
After the same operation as the last, did not find reproduce. 
Thank you very much to thank me, not in time with the test, it is really sorry. 
Thank you for providing such a framework!

**Comment by Ereza** [comment]
Thanks for your feedback @zengcanxiang, I'll make a new release of the library when I have some free time :)
