### ISSUE TITLE
[Compatibility] Extending AppCompatActivity instead of Activity for DefaultErrorActivity

### ISSUE THREAD

**Issue by herbeth1u** [Ereza/CustomActivityOnCrash#30]
Hello!

**Current situation:** Currently, _DefaultErrorActivity_ extends _Activity_, which looks great for API >= 21 devices. However, the problem is that pre-Lollipop devices still have to use the old Holo theme. So the look on these devices is hard to customize, not uniform with the post-Lollipop Material look, and forces the developer to create multiple style files, like this one : https://github.com/Ereza/CustomActivityOnCrash/blob/master/library/src/main/res/values-v14/styles.xml

**Solution:** It may be easier for everyone to make _DefaultErrorActivity_ extend _AppCompatActivity_ instead, making use of the support lib to make everything homogeneous, easier to customize and keeping a unique style.xml file with a theme extending _Theme.AppCompat_. 
As far as I know, modifying the parent class is the only thing to do, and it pains me to create my own error activity class just to do so (because that's the only thing that keeps me from using the default error activity class).

By the way, that might also explain why issue #26 (which uses an AppCompat theme) still doesn't seem to work if I believe the last comment, though I haven't investigated the issue further.

Also, I may have overlooked a problem so let me know if it's not doable.
Thanks!

**Comment by Ereza** [comment]
Hi @herbeth1u, sorry for the long time without replying.

I agree it's about time to make the library minSdkVersion 14, so this means we can add AppCompat. It's done in the current development version, which will be released soon as 2.0.0.

Thanks for reporting the issue.

**Comment by Ereza** [comment]
Hi, the latest version is now on Maven Central.
