### ISSUE TITLE
how to solve unfortunately myapp has stopped?

### ISSUE THREAD

**Issue by palashmandokhot** [Ereza/CustomActivityOnCrash#33]
**how to solve unfortunately myapp has stopped?**

**Comment by Ereza** [comment]
Not enough info. Please reopen with a more detailed explanation if needed.

**Comment by palashmandokhot** [comment]
hi,
thanks for you reply after my coding and project just a done then i want to see my app hows working so i try to install my app in android phone for just testing purpose so everything look like fine but after turn of oppening my app so it closed and one dialog box shows Unfortunately myapp has stopped and i cant see my app hows working and features that i add it working or not so can you please help me?
