### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by AdityaAnand1** [Ereza/CustomActivityOnCrash#34]
Been a while since any activity... I'm just wondering whether this library still works.

**Comment by Ereza** [comment]
Yes, it does work. I am working on a new version with some changes, the most critical of which is adding Firebase compatibility. Currently if you have Firebase Crash Reporting in your app, CustomActivityOnCrash will not invoke Firebase's `UncaughtExceptionHandler` and you will get no crash reports in Firebase. That will be fixed on the next version.

**Comment by Ereza** [comment]
Hi @AdityaAnand1 , the latest version is already released on Maven Central.

**Comment by AdityaAnand1** [comment]
@Ereza Thanks for the reply! I'll go and check out the new version now :)
