### ISSUE TITLE
Stacktrace doesn't show up on Android Studio

### ISSUE THREAD

**Issue by Sloy** [Ereza/CustomActivityOnCrash#35]
Hi!

Android Studio only shows the logcat of the current process by default. 
Since the library restarts the process to show the error Activity, and the stacktrace of the crash is logged in the old process, Android Studio doesn't show the stacktrace after a crash. You need to change the filters, or remove them, showing a lot of [unwanted verbose information](https://stackoverflow.com/questions/22163376/samsung-phones-emit-a-lot-of-log-messages-on-logcat).

So, here's my idea for that problem:
The library could log the info in `getStackTraceFromIntent`() or `getAllErrorDetailsFromIntent()` from the error Activity. This way the developer will see it in Android Studio without changing the filter. The info will be duplicated in the full logcat, but I think its an acceptable trade-off.

That's what I've done in our custom error Activity at InfoJobs, but I think it could be a helpful addition to the library itself.

What do you think? 
Thanks again for the library @Ereza, you know we're happy users of it :)

**Comment by Ereza** [comment]
Hi @Sloy, thanks again for the positive feedback! Yes, that's an issue I have faced myself, and I think it would indeed be a nice addition. I'll add it :)

**Comment by Ereza** [comment]
Done in 2.2.0. Thanks again for the suggestion ;)
