### ISSUE TITLE
show custom crash activity

### ISSUE THREAD

**Issue by MahdiPishguy** [Ereza/CustomActivityOnCrash#39]
i added this line into main activity:

`throw new RuntimeException("Boom!");`

and configure library on application class:

```
   CaocConfig.Builder.create()
           .backgroundMode(CaocConfig.BACKGROUND_MODE_SILENT) //default: CaocConfig.BACKGROUND_MODE_SHOW_CUSTOM
           .enabled(false)
           .showErrorDetails(false)
           .showRestartButton(false)
           .trackActivities(true)
           .minTimeBetweenCrashesMs(2000)
           .errorDrawable(R.mipmap.ic_launcher_round)
           .restartActivity(null)
           .errorActivity(CrashActivity.class)
           .eventListener(new CustomEventListener())
           .apply();
```

manifest:

```
   <activity
       android:name=".Ui.CrashActivity"
       android:configChanges="screenSize|orientation"/>
```

`restartActivity` is null here and after launch application that cause of restarting to loop and i don't see crash activity

**Comment by Ereza** [comment]
Hi @MahdiPishguy, you are setting .enabled(false), this disables the crash interception mechanism and is not supposed to be used by the majority of apps. You copied the customization example, but you should only set the parameters you wish to change, not all of them.
