### ISSUE TITLE
log exception to file

### ISSUE THREAD

**Issue by lengxuegang** [Ereza/CustomActivityOnCrash#41]
is there any requirements of logging exceptions into files?

**Comment by Polyterative** [comment]
This would be great

**Comment by Ereza** [comment]
Hi, thanks for the suggestion and sorry for the lack of updates.

What would you like to do, exactly? What's the point of writing to a file?

You can already execute custom logic when a crash occurs, by registering an `EventListener` and overriding the `onLaunchErrorActivity` method. This is executed *BEFORE* the crashed process gets killed, so you should be able to get all the info you need.

If you need any other thing please let me know!

**Comment by Polyterative** [comment]
> You can already execute custom logic when a crash occurs

At this point I have all I need

**Comment by Ereza** [comment]
Closing this then. If you feel you need anything more feel free to reopen it!
