### ISSUE TITLE
stacktrace doesn't help sometimes

### ISSUE THREAD

**Issue by android-dataticket** [Ereza/CustomActivityOnCrash#45]
my app sent me two identical stacktraces from two different units/users coincidentally using the same device type and android 7.0

usually, the stacktraces that come in will have something in it that points me to some part of code in my app that I can goto and debug, but these two stacktraces do not point to any of my own code, its just all android stuff... how can i tell what part of my code caused the nullpointerexception?

Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference at android.widget.FrameLayout.layoutChildren(FrameLayout.java:275) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:18874) at android.view.ViewGroup.layout(ViewGroup.java:5954) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:18874) at android.view.ViewGroup.layout(ViewGroup.java:5954) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:18874) at android.view.ViewGroup.layout(ViewGroup.java:5954) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at android.view.View.layout(View.java:18874) at android.view.ViewGroup.layout(ViewGroup.java:5954) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) at android.widget.FrameLayout.onLayout(FrameLayout.java:261) at com.android.internal.policy.DecorView.onLayout(DecorView.java:935) at android.view.View.layout(View.java:18874) at android.view.ViewGroup.layout(ViewGroup.java:5954) at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2697) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959) at android.view.Choreographer.doCallbacks(Choreographer.java:734) at android.view.Choreographer.doFrame(Choreographer.java:670) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6776) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by Ereza** [comment]
Hi,

This issue has nothing to do with the library. You have some kind of crash, if you got it on Crashlytics or similar and it's an internal Android crash, there is probably nothing you can do. You can try asking a question on StackOverflow however, not here.

I'll close this, if you have any problem with the library open a new issue.

**Comment by android-dataticket** [comment]
Thanks, I didn't mean to make an issue but I wanted to get your input on the stacktrace :(
