### ISSUE TITLE
the last version not found in repo

### ISSUE THREAD

**Issue by Paul75** [Ereza/CustomActivityOnCrash#48]
Hello,

The last version not found in repo ?

compile 'cat.ereza:customactivityoncrash:2.2.0' give me : 

`Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve cat.ereza:customactivityoncrash:2.2.0.`

Thanks

**Comment by Ereza** [comment]
Hi, sorry for the late response.

Version 2.2.0 is in Maven Central since November 20th: https://mvnrepository.com/artifact/cat.ereza/customactivityoncrash

Check that you are not working in offline mode or any other connectivity issue.
