### ISSUE TITLE
Get Error Activity from AndroidManifest.xml

### ISSUE THREAD

**Issue by alorma** [Ereza/CustomActivityOnCrash#5]
As discussed in https://github.com/Ereza/CustomActivityOnCrash/issues/4, it will be great if we can set an error Activity directly from AndroidManifest.xml, so we only need to add this line:

```java
 CustomActivityOnCrash.install(this);
```

Maybe it can add a custom action in order to be launched from library:

```xml
        <activity
            android:name=".view.activity.ErrorActivity">
            <intent-filter>
                <action android:name="cat.ereza.customactivityoncrash.ERROR" />
            </intent-filter>
        </activity>
```

As discussed, it will work like:

* **Prioritary**: ```CustomActivityOnCrash.setErrorActivityClass(CustomErrorActivity.class);```
* **Secondary**: Manifest action
* **Less important**: Default error activity.

**Comment by AizazAZ** [comment]
I have created new pull request with this change, please review.

**Comment by Ereza** [comment]
Implemented. Thanks!
