### ISSUE TITLE
Enable auto linking for the error_occurred_explanation text view

### ISSUE THREAD

**Issue by erijo** [Ereza/CustomActivityOnCrash#51]
It would be nice if http links included in a custom explanation (suck as links to GitHub issues) could be clickable. Setting android:autoLink="web|email" on the text view seems like it would do the trick.

**Comment by Ereza** [comment]
Hi,

I think adding `autoLink` to the `TextView` could add additional issues to the library, so I won't do it for now. The best solution if you need further customization is to implement your own `ErrorActivity`.

Thanks for your report!
