### ISSUE TITLE
help error when debug.

### ISSUE THREAD

**Issue by lucazin** [Ereza/CustomActivityOnCrash#54]
when i try to debug after add customcrash i have this problem

import android.support.v7.app.NotificationCompat;

Error:(33, 30) error: cannot find symbol class NotificationCompat

and i use for notifications.

**Comment by Ereza** [comment]
I don't think this error should have anything to do with the library.

In case it's a dependency problem, please try with the upcoming version that changes dependencies to AndroidX.

Closing this for now.
