### ISSUE TITLE
How to disable logs in your library, its populating my logcat with many lines

### ISSUE THREAD

**Issue by asif84468** [Ereza/CustomActivityOnCrash#55]
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state =  0, nProtocol = 6, front = sl, nSrcAddrV6 = $�, tempFilter.srcPort= 0, nDestAddrV6 =x���}, tempFilter.dstPort=0, rest =
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    0: 00000000000000000000000000000000:A9AE 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33889 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 0:, nSrcAddrV6 = ::, tempFilter.srcPort= A9AE, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    1: 00000000000000000000000000000000:1F90 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000 10197        0 19646972 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Converting filter family to v4
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Add filter for AF=2, protocol=6, nSrcAddrV6 = ::, sport=901F, nDestAddrV6 =::, dport=0,
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    2: 00000000000000000000000000000000:9C70 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33909 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 2:, nSrcAddrV6 = ::, tempFilter.srcPort= 9C70, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    3: 00000000000000000000000000000000:AE94 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33893 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.661   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 3:, nSrcAddrV6 = ::, tempFilter.srcPort= AE94, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    4: 00000000000000000000000000000000:A656 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33913 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 4:, nSrcAddrV6 = ::, tempFilter.srcPort= A656, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    5: 00000000000000000000000000000000:A7BA 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33901 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 5:, nSrcAddrV6 = ::, tempFilter.srcPort= A7BA, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    6: 00000000000000000000000000000000:9D9A 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33897 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 6:, nSrcAddrV6 = ::, tempFilter.srcPort= 9D9A, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    7: 00000000000000000000000000000000:A79C 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33905 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 7:, nSrcAddrV6 = ::, tempFilter.srcPort= A79C, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    8: 0000000000000000FFFF00006401A8C0:98A0 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000 10152        0 19293995 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Converting filter family to v4
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Add filter for AF=2, protocol=6, nSrcAddrV6 = ::ffff:192.168.1.100, sport=A098, nDestAddrV6 =::, dport=0,
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing    9: 00000000000000000000000000000000:E981 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000 10152        0 19298519 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Converting filter family to v4
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Add filter for AF=2, protocol=6, nSrcAddrV6 = ::, sport=81E9, nDestAddrV6 =::, dport=0,
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   10: 00000000000000000000000000000000:9F63 00000000000000000000000000000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 33885 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Skip non-listening tcp6 Socket: state = 8A, nProtocol = 6, front = 10:, nSrcAddrV6 = ::, tempFilter.srcPort= 9F63, nDestAddrV6 =::, tempFilter.dstPort=0, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   11: 0000000000000000FFFF00000100007F:9AEC 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000 10152        0 19298756 1 0000000000000000 100 0 0 10 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Converting filter family to v4
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Add filter for AF=2, protocol=6, nSrcAddrV6 = ::ffff:127.0.0.1, sport=EC9A, nDestAddrV6 =::, dport=0,
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   12: 0402052437839594F0312C2C0EEB9A25:B04E 0068042408080940000000000A200000:01BB 08 00000000:00000001 00:00000000 00000000 10040        0 19338642 1 0000000000000000 29 4 28 10 1400
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: dstAddr.v6.s6_addr does not match addrV6Any Socket: state =  8, nProtocol = 6, front = 12:, nSrcAddrV6 = 2405:204:9495:8337:2c2c:31f0:259a:eb0e, tempFilter.srcPort= B04E, nDestAddrV6 =2404:6800:4009:808::200a, tempFilter.dstPort=1BB, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   13: 0000000000000000FFFF00006401A8C0:9E1E 0000000000000000FFFF00007C481517:01BB 01 00000000:00000000 00:00000000 00000000 10197        0 19647643 1 0000000000000000 93 4 25 10 1400
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: dstAddr.v6.s6_addr does not match addrV6Any Socket: state =  1, nProtocol = 6, front = 13:, nSrcAddrV6 = ::ffff:192.168.1.100, tempFilter.srcPort= 9E1E, nDestAddrV6 =::ffff:23.21.72.124, tempFilter.dstPort=1BB, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   14: 0402052437839594F0312C2C0EEB9A25:BC1B 8028032A0F002FF00CB0CEFA02000000:01BB 08 00000000:00000000 00:00000000 00000000 10113        0 19494044 1 0000000000000000 29 4 30 10 1400
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: dstAddr.v6.s6_addr does not match addrV6Any Socket: state =  8, nProtocol = 6, front = 14:, nSrcAddrV6 = 2405:204:9495:8337:2c2c:31f0:259a:eb0e, tempFilter.srcPort= BC1B, nDestAddrV6 =2a03:2880:f02f:f:face:b00c:0:2, tempFilter.dstPort=1BB, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   15: 0402052437839594F0312C2C0EEB9A25:A8FB 00680424060809400000000002200000:01BB 08 00000000:000001A1 00:00000000 00000000 10125        0 19612411 1 0000000000000000 43 4 30 10 1400
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: dstAddr.v6.s6_addr does not match addrV6Any Socket: state =  8, nProtocol = 6, front = 15:, nSrcAddrV6 = 2405:204:9495:8337:2c2c:31f0:259a:eb0e, tempFilter.srcPort= A8FB, nDestAddrV6 =2404:6800:4009:806::2002, tempFilter.dstPort=1BB, rest = 0
[ 03-09 11:26:47.662   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   16: 0402052437839594F0312C2C0EEB9A25:A8FB 8028032A80002FF10CB0CEFAA01E0000:01BB 01 00000000:00000000 00:00000000 00000000 10113        0 19649495 1 0000000000000000 27 4 32 10 1400
[ 03-09 11:26:47.663   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: dstAddr.v6.s6_addr does not match addrV6Any Socket: state =  1, nProtocol = 6, front = 16:, nSrcAddrV6 = 2405:204:9495:8337:2c2c:31f0:259a:eb0e, tempFilter.srcPort= A8FB, nDestAddrV6 =2a03:2880:f12f:80:face:b00c:0:1ea0, tempFilter.dstPort=1BB, rest = 0
[ 03-09 11:26:47.663   971: 1035 D/         ]
DpmQmiUtils::parseSocketLine: Now Parsing   17: 0402052437839594F0312C2C0EEB9A25:AFE0 8028032A83002FF10CB0CEFADE250000:01BB 08 00000000:00000000 00:00000000 00000000 10113        0 19494049 1 0000000000000000 29 4 30 10 1400

**Comment by Ereza** [comment]
These logs are not produced by the library. Please check your other code.
