### ISSUE TITLE
NPE in getConfigFromIntent

### ISSUE THREAD

**Issue by rubengees** [Ereza/CustomActivityOnCrash#56]
I received several crash reports in the Developer Console.

This is the relevant part of the stacktrace:

```java
Caused by: java.lang.NullPointerException: 
  at cat.ereza.customactivityoncrash.config.CaocConfig.isLogErrorOnRestart (CaocConfig.java:90)
  at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getConfigFromIntent (CustomActivityOnCrash.java:280)
```

It seems that this is caused by a missing `null` check here:

https://github.com/Ereza/CustomActivityOnCrash/blob/edd5bb625d12bdf87c29039a27e48251f7f47f1b/library/src/main/java/cat/ereza/customactivityoncrash/CustomActivityOnCrash.java#L280

**Comment by gavingt** [comment]
I'm beginning to think that this is the result of some sort of Google crawler bot. The one user this happens to is based in Czechia, and always seems to update my app and use it within a couple hours of me pushing a new version (regardless of time of day). I haven't had any users buy my app in Czechia. And the only way this could be happening is if the user is opening Activities programmatically (like using ADB), and thus the intent extras aren't being sent/received as they should.

**Comment by Ereza** [comment]
Yep, seems that something is launching the ErrorActivity directly and not from inside the library. I added however a null checkso it should not happen anymore.

This will be fixed in the next release. Thanks for your report!
