### ISSUE TITLE
Need Help about CustomCrashActivity

### ISSUE THREAD

**Issue by onuryurtturk** [Ereza/CustomActivityOnCrash#59]
Hi there!,
Im using these configs. I tried each of them but i cant see crash activity. Library only restarting app. 
Can you appoint whats wrong?
-----------------------------------------------------------------------------------------------------------
          CaocConfig.Builder.create()
                .backgroundMode(CaocConfig.BACKGROUND_MODE_SHOW_CUSTOM) //default: CaocConfig.BACKGROUND_MODE_SHOW_CUSTOM
                .enabled(true) //default: true
                .showErrorDetails(true) //default: true
                .showRestartButton(true) //default: true
                .logErrorOnRestart(true) //default: true
                .trackActivities(true) //default: false
                .minTimeBetweenCrashesMs(3000) //default: 3000
                .errorDrawable(R.drawable.launcher) //default: bug image
                .restartActivity(SplashScreen.class) //default: null (your app's launch activity)
                .errorActivity(CustomCrashActivity.class) //default: null (default error activity)
                .apply();
----------------------------------------------------------------------------------------------------------
        CaocConfig.Builder.create().apply();

Thnks

**Comment by Ereza** [comment]
Closing this because it's an old issue. If you still need assistance, please reopen it! Sorry for the inconvenience!
