### ISSUE TITLE
how to solve unfortunately myapp has stopped?

### ISSUE THREAD

**Issue by palashmandokhot** [Ereza/CustomActivityOnCrash#69]
hi,
after my coding and project just a done then i want to see my app hows working so i try to install my app in android phone for just testing purpose so everything look like fine but after turn of oppening my app so it closed and one dialog box shows Unfortunately myapp has stopped and i cant see my app hows working and features that i add it working or not so can you please help me?
i am using android 5.1 above

**Comment by Ereza** [comment]
Not enough information to know if this is related to the library in any way. This is not the place for basic Android development questions, please check your logcat. Feel free to reopen if there is any issue with the library itself and provide more info.
