### ISSUE TITLE
Deleted everthing on my phone

### ISSUE THREAD

**Issue by PROSKEY** [Ereza/CustomActivityOnCrash#83]
This library deleted everything from my external storage. 
this is how it happened. 
added library to the project using gradle without adding any code and it worked perfectly except that share button, on clicking on the share button in crash reporting screen, application again crashes 

Crash was this : android.os.FileUriExposedException: file:///.... exposed beyond app through Intent.getData()

then i tried to store that log in my external storage on root directory by adding line which is mentioned in wiki. this made things worse. the number log entry drastically increased without any crashes or exception, clicked on delete button and boom. precious files gone.

**Comment by Ereza** [comment]
Did it also eat your lunch and kill your family?

Don't blame this library for your own mistakes. The library does not even require any permission to write to your external storage, and whatever you include in the listeners provided by the library is YOUR code, so: your code, your mistakes.

**Comment by PROSKEY** [comment]
@Ereza yes if it could, it would have eaten my lunch too. ;)
sorry but it was not caused by your library. it was caused by other crash reporting library. and i reported it here by mistake.
Initially i planned to use your library but i didn't see any option to share crash logs from app directly, and the other library which had this functionality did all this to make my day worse.
