### ISSUE TITLE
Is this testable?

### ISSUE THREAD

**Issue by cheskos** [Ereza/CustomActivityOnCrash#84]
Hi. Is there a way to test this with Robolectric? Or with any test framework for that matter. I haven't been able to by just throwing an exception in the test method or by posting it to main looper. 

BTW, I'm targeting and running in API 17 and MultiDex works :)

Thank you for your time.

**Comment by Ereza** [comment]
Hi there, sorry for taking so long to reply. I don't have any experience with Robolectric nor testing in general, but I don't think it's easy to test this (at least, as a unit test). When a crash occurs, the OS kills the current process completely and a new process is launched (which shows CustomActivityOnCrash error activity when launched).
