### ISSUE TITLE
call api before crash

### ISSUE THREAD

**Issue by fukemy** [Ereza/CustomActivityOnCrash#88]
hi, im using webrtc to call function, but i got some unexpected crash so server can not recognized whether device is connected or not, so i want to call api leave call before crash, can u teach me how to do it? Thanks

**Comment by Ereza** [comment]
I'm sorry, but this does not seem like an issue related to CustomActivityOnCrash.
Also, calling an API during a crash is not possible and even if possible, should not be done as you would be blocking the main thread.
